### ISSUE TITLE
Skip these domains when looking up company data

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-clearbit#10]
We should protect the flow creator from generating a bunch of requests to Clearbit, when it's obvious that they will not get applicable data back. Prior to sending the request to Clearbit, ensure that the domain to be queried is not on this list:
* gmail.com
* yahoo.com
* hotmail.com
* live.com
* outlook.com
* icloud.com

**Comment by cgrayson** [comment]
Fixed in version 0.0.9.
