### ISSUE TITLE
Please remove clearbit pricing for now

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-clearbit#21]
We need to modify the pricing for Clearbit as they've changed their setup. I don't have the new price yet, but it is definitely going to be more than 1¢ per call, so please replace the price in the UI with this for now: "Contact your account manager for pricing information."

Thanks

**Comment by justinwinslow** [comment]
Fixed with: https://github.com/activeprospect/leadconduit-client/commit/9696174004bb67d0eb1ff48242fbf21b39fbbe1b

**Comment by justinwinslow** [comment]
This will be deployed with the next UI release
