### ISSUE TITLE
company_lookup.billable variable should be a number type

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-clearbit#22]
https://github.com/activeprospect/leadconduit-integration-clearbit/blob/206371416193d98584809e8f52118c52a846aa0f/src/company_lookup.coffee#L102

Because the type is set to "string", the `billable` numeric value is converted to a string before it gets to the handler. The handler only records the `billable` property if it is a number. So this is causing us not to bill for this integration.

**Comment by jgrayson676** [comment]
fixed in #23
