### ISSUE TITLE
fall back to the domain from `lead.email` if `lead.website` not set

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-clearbit#9]
But if that domain is one of the big email services (gmail.com et al, list forthcoming from @alexj), then don't. Think that check could go in `validate()`, so that a skip reason is visible on such leads.

**Comment by alexj** [comment]
See https://github.com/activeprospect/leadconduit-integration-clearbit/issues/10 for the list

**Comment by cgrayson** [comment]
Fixed in version 0.0.9.
